### ISSUE TITLE
parser taking first element inappropriately?

### ISSUE THREAD

**Issue by swadey** [abeschneider/PEGParser.jl#12]
Oddly strings returned by an action are being truncated to the first element.  See below:
```julia
using PEGParser

@grammar test begin
  stringy = r"\".*?\"" { _0 }
  start = stringy { _1 }
end

println(parse(test, "\"test\""))
```

This returns:
```
('"',7,nothing)
```
I would have expected `"test"`

**Comment by abeschneider** [comment]
Hmm. That is because `start` is not always an array, which might be undesirable behavior.

Currently, you would have to do:

```
@grammar test begin
  stringy = r"\".*?\"" { _0 }
  start = stringy { children }
end
```

because `children` ends up just being `stringy`.That said, I can see how that might be potentially confusing. I'll look into changing that behavior.

**Comment by abeschneider** [comment]
Okay, it looks like referenced rules were not properly kept as arrays when acting as children nodes. I've tested your code, and it produces the expected results now.

See commit d5c0ab0862478e2f65717ca74982efbe128dc295
