### ISSUE TITLE
Examples fail to run after installation

### ISSUE THREAD

**Issue by smartmic** [abeschneider/PEGParser.jl#13]
I have a vanilla Julia installation and wanted to try PEGParser for development of a simple DSL. I installed via Pkg and manually, but the examples failed to run in both cases, e.g.:
```
julia calc1.jl
ERROR: `parse` has no method matching parse(::Grammar, ::AndRule, ::ASCIIString, ::Int32, ::Nothing)
 in parse at /home/martin/.julia/v0.3/PEGParser.jl/src/PEGParser.jl:33
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /tmp/calc1.jl, in expression starting on line 16

```

**Comment by abeschneider** [comment]
Hmm.. that's strange. That function is defined in `PEGParser.jl`, so not finding it would seem to indicate a possible issue with loading the library.

 I removed my current Pkg'd installed version and reinstalled it, but was not able to replicate the problem. Can you verify the version you're using with `Pkg.status()`? Also, what happens when you do `Pkg.test("PEGParser")`?

Finally, what version of Julia are you using? I'm currently testing on `0.3.5-pre+121`. It has not been tested on the `0.4.x` branch.

**Comment by abeschneider** [comment]
@smartmic Any luck with getting the examples to run? If I don't hear otherwise, I'll consider this issue closed.

**Comment by smartmic** [comment]
It is indeed strange, I use julia 0.3.9, the PEGParser is version 0.1.0. My assumption is that is has to do with my Julia installation, I use the precompiled Linux 32bit binary. I could not reproduce the error on a different 64bit installation on my server. Because of this, I think the problem lies not in your package, what do you mean? Thank you anyhow.

For your information, here is the output of ``Pkg.test("PEGParser")`` 
```
julia> Pkg.test("PEGParser")
INFO: Testing PEGParser
ERROR: `ListRule` has no method matching ListRule(::ASCIIString, ::ReferencedRule, ::Terminal, ::Int32)
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /home/martin/.julia/v0.3/PEGParser/test/ParserTests.jl, in expression starting on line 390
while loading /home/martin/.julia/v0.3/PEGParser/test/runtests.jl, in expression starting on line 1

=====================================================================================[ ERROR: PEGParser ]=====================================================================================

failed process: Process(`/home/martin/ressources/julia-31efe690be/bin/julia /home/martin/.julia/v0.3/PEGParser/test/runtests.jl`, ProcessExited(1)) [1]

==============================================================================================================================================================================================
INFO: No packages to install, update or remove
ERROR: PEGParser had test errors
 in error at error.jl:21
 in test at pkg/entry.jl:718
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in cd at pkg/dir.jl:28
 in test at pkg.jl:67
```

**Comment by abeschneider** [comment]
Okay, I figured it out. The issue is that I use `Int64` for a parameter type, which for obvious reasons, doesn't exist for the 32-bit version of Julia. The correct thing is for me to change the parameter to just `Int`. I'll should be able to update the code in the near future.

**Comment by smartmic** [comment]
Great! Thank you.
