### ISSUE TITLE
Ignore keyword in transform function not working

### ISSUE THREAD

**Issue by smartmic** [abeschneider/PEGParser.jl#14]
The ``ignore`` functionality for transforming an AST is documented in *index.rst* and used in an experimental example. But the ``transform`` function failed to run with a defined ignore list:
```
ERROR: function transform does not accept keyword arguments
```

**Comment by abeschneider** [comment]
Unfortunately I haven't gotten around to updating `index.rst`. I removed the ignore list because the same functionality can be achieved in the grammar itself with ignores.

If you can provide me with an example of what you are trying to do, I can probably suggest an alternative.

**Comment by smartmic** [comment]
I was just looking at the example dot.jl. I am planning to implement a DSL with a similar syntax where I want to use the transformed AST objects for further processing. Therefore I need 'clean' data structures. In case of the dot.jl example, without the ̀``ignore`` keyword, I get:
```
{{{},{}},{{},{}},{{GraphNode({"nodeA",{}})},{GraphEdge({"nodeA",{}},{{},{}})},{GraphEdge({"nodeB",{}},{{
},{}})}},{{},{}}}
```
I am looking for something where I have 
```
{{GraphNode({"nodeA"}),GraphEdge({"nodeA","nodeC"}), … }}
```
or even simpler.

**Comment by abeschneider** [comment]
You can do something like this (will update repository with new version when I get a chance):

```julia
using PEGParser

type GraphNode
  name
end

type GraphEdge
  from
  to
end

type Graph
  nodes::Array{GraphNode}
  edges::Array{GraphEdge}

  function Graph(children)
    nodes = filter ((child) -> typeof(child) == GraphNode, children)
    edges = filter ((child) -> typeof(child) == GraphEdge, children)

    return new(nodes, edges)
  end
end

@grammar test begin
  start = (graph_label + lbrace + stmt_lst + rbrace) { _3 }
  stmt_lst = list(stmt, space + ?(semicolon)) { Graph(children) }
  stmt = edge_stmt | node_stmt
  node_stmt = node_id { GraphNode(_1) }
  edge_stmt = (node_id + edgeop + node_id) { GraphEdge(_1, _3) }

  node_id = node_id_value { _1 }
  node_id_value = (r"[a-zA-Z][a-zA-Z0-9]*" + -space) { _1.value }
  graph_label = "graph" + space
  semicolon = ";" + space
  lbrace = "{" + space
  rbrace = "}" + space
  edgeop = "->" + space
  space = r"[ \t\n\r]*"
end

parse_data = """
graph {
  nodeA
  nodeA -> nodeC
  nodeB -> nodeC
}
"""

(graph, pos, error) = parse(test, parse_data)
println("nodes = ", graph.nodes)
println("edges = ", graph.edges)
```

The (somewhat) newly added semantic actions (`{ _i}`) allow you to apply some operation (or simply return) the children of the node. Thus, you can build up data structures (such as `Graph`) as you're parsing.

Technically transforms aren't required anymore. However, they allow further modification of the AST if required (e.g. you may have several types of outputs required, in which case you'll want to delay those operations until later).

**Comment by smartmic** [comment]
Thank you. This help a lot.
