### ISSUE TITLE
Support for Julia 0.4(+)

### ISSUE THREAD

**Issue by bnewbold** [abeschneider/PEGParser.jl#22]
PEGParser.jl currently requires julia 0.3 (in the REQUIRE file). Is there any plan to or interest in supporting Julia 0.4 or future versions?

**Comment by abeschneider** [comment]
I've updated the REQUIRE along with some testing of the code (previous work was done to make everything compatible with 0.4, but 0.4.5 caused more compatibility issues).

For some of the examples there is still the warning:

> WARNING: [a] concatenation is deprecated; use collect(a) instead

which I have to chase down before I create a new version. Until then, the current committed version should work (let me know if you encounter any other issues).
